<template>
  <div :class="[
    compact ? '' : 'bg-white shadow rounded-lg'
  ]">
    <!-- Loading State -->
    <div v-if="loading" :class="[
      'flex items-center justify-center',
      compact ? 'py-8' : 'py-12'
    ]">
      <div class="spinner"></div>
      <span class="ml-2 text-gray-500">Loading articles...</span>
    </div>

    <!-- Empty State -->
    <div v-else-if="articles.length === 0" :class="[
      'text-center',
      compact ? 'py-8' : 'py-12'
    ]">
      <NewspaperIcon class="mx-auto h-12 w-12 text-gray-400" />
      <h3 class="mt-2 text-sm font-medium text-gray-900">
        {{ emptyStateTitle }}
      </h3>
      <p class="mt-1 text-sm text-gray-500">
        {{ emptyStateDescription }}
      </p>
      <div class="mt-6" v-if="showBrowseButton">
        <router-link
          to="/feeds"
          class="inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700"
        >
          <PlusIcon class="-ml-1 mr-2 h-4 w-4" />
          Browse Feeds
        </router-link>
      </div>
    </div>

    <!-- Articles List -->
    <div v-else class="divide-y divide-gray-200" data-no-translate data-no-accessibility>
      <article
        v-for="article in displayedArticles"
        :key="article.id"
        :class="[
          'hover:bg-gray-50 transition-colors duration-200',
          compact ? 'p-4' : 'p-6'
        ]"
        data-no-translate
        data-no-accessibility
      >
        <div class="sm:flex sm:items-start sm:space-x-4">
          <div class="flex-1 min-w-0 article-content">
            <!-- Article Title -->
            <h3 :class="[
              'font-semibold text-gray-900 hover:text-primary-600 cursor-pointer mb-3 leading-relaxed font-reading',
              compact ? 'text-sm' : 'text-xl'
            ]">
              <a 
                :href="article.link || article.url" 
                target="_blank" 
                rel="noopener noreferrer"
                class="hover:underline"
              >
                {{ cleanContent(article.title) }}
              </a>
            </h3>

            <!-- Article Preview / Summary -->
            <div v-if="article.hasSummary && article.summary" class="mb-4">
              <div class="p-4 bg-blue-50 rounded-md border-l-4 border-blue-200">
                <h4 class="text-sm font-semibold text-blue-800 mb-2">AI Summary</h4>
                <p :class="[
                  'leading-relaxed text-blue-900 font-reading',
                  compact ? 'text-sm' : 'text-base'
                ]">{{ article.summary.text }}</p>
                <div class="mt-3 text-sm text-blue-600">
                  Generated by {{ article.summary.aiModel }} • {{ formatDate(article.summary.createdAt) }}
                </div>
              </div>
            </div>
            <p v-else :class="[
              'leading-relaxed text-gray-700 mb-4 font-reading',
              compact ? 'text-sm line-clamp-2' : 'text-base line-clamp-3'
            ]">
              {{ cleanContent(article.contentPreview || article.description) }}
            </p>

            <!-- Action Buttons (Mobile - below content, above meta) -->
            <div v-if="showActions" class="sm:hidden mb-3">
              <div class="flex items-center gap-2">
                <a
                  :href="article.link || article.url"
                  target="_blank"
                  rel="noopener noreferrer"
                  class="inline-flex items-center px-3 py-1 border border-gray-300 text-xs font-medium rounded text-gray-700 bg-white hover:bg-gray-50"
                >
                  <ArrowTopRightOnSquareIcon class="h-3 w-3 mr-1" />
                  Read
                </a>
                
                <!-- Delete Button (Mobile) -->
                <button
                  v-if="showDeleteButton"
                  @click="handleDeleteClick(article.id)"
                  :disabled="deletingArticle[article.id]"
                  class="inline-flex items-center px-3 py-1 border border-red-300 text-xs font-medium rounded text-red-700 bg-red-50 hover:bg-red-100 disabled:opacity-50"
                >
                  <span v-if="deletingArticle[article.id]" class="spinner-sm mr-1"></span>
                  <TrashIcon v-else class="h-3 w-3 mr-1" />
                  Delete
                </button>
                
                <!-- Summary Button (Mobile) -->
                <button
                  v-if="!article.hasSummary"
                  @click="generateSummary(article.id)"
                  :disabled="generatingSummary[article.id]"
                  class="inline-flex items-center px-3 py-1 border border-transparent text-xs font-medium rounded text-primary-700 bg-primary-100 hover:bg-primary-200 disabled:opacity-50"
                >
                  <span v-if="generatingSummary[article.id]" class="spinner-sm mr-1"></span>
                  Summarize
                </button>
              </div>
            </div>

            <!-- Article Meta -->
            <div :class="[
              'flex items-center space-x-4 text-gray-500 mb-3',
              compact ? 'text-xs' : 'text-xs'
            ]">
              <span class="font-medium">{{ article.feedName || article.feed?.title }}</span>
              <span>•</span>
              <span>{{ formatDate(article.pubDate) }}</span>
              <span v-if="article.author">•</span>
              <span v-if="article.author">{{ article.author }}</span>
            </div>

            <!-- Categories -->
            <div v-if="article.categories && article.categories.length > 0 && !compact" class="mb-3">
              <div class="flex flex-wrap gap-1">
                <span
                  v-for="category in article.categories.slice(0, 3)"
                  :key="category"
                  class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-800"
                >
                  {{ category }}
                </span>
                <span
                  v-if="article.categories.length > 3"
                  class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-800"
                >
                  +{{ article.categories.length - 3 }} more
                </span>
              </div>
            </div>
          </div>

          <!-- Article Actions - Desktop (hidden on mobile) -->
          <div v-if="showActions" class="hidden sm:flex flex-shrink-0 flex-col space-y-2">
            <!-- External Link Button -->
            <a
              :href="article.link || article.url"
              target="_blank"
              rel="noopener noreferrer"
              class="inline-flex items-center px-3 py-1 border border-gray-300 text-xs font-medium rounded text-gray-700 bg-white hover:bg-gray-50"
            >
              <ArrowTopRightOnSquareIcon class="h-3 w-3 mr-1" />
              Read
            </a>

            <!-- Delete Button -->
            <button
              v-if="showDeleteButton"
              @click="handleDeleteClick(article.id)"
              :disabled="deletingArticle[article.id]"
              class="inline-flex items-center px-3 py-1 border border-red-300 text-xs font-medium rounded text-red-700 bg-red-50 hover:bg-red-100 disabled:opacity-50"
            >
              <span v-if="deletingArticle[article.id]" class="spinner-sm mr-1"></span>
              <TrashIcon v-else class="h-3 w-3 mr-1" />
              Delete
            </button>

            <!-- Summary Button -->
            <button
              v-if="!article.hasSummary"
              @click="generateSummary(article.id)"
              :disabled="generatingSummary[article.id]"
              class="inline-flex items-center px-3 py-1 border border-transparent text-xs font-medium rounded text-primary-700 bg-primary-100 hover:bg-primary-200 disabled:opacity-50"
            >
              <span v-if="generatingSummary[article.id]" class="spinner-sm mr-1"></span>
              Summarize
            </button>
          </div>
        </div>
      </article>
    </div>

    <!-- View More Link (for compact/dashboard view) -->
    <div v-if="showViewMore && articles.length > 0" :class="[
      'text-center border-t border-gray-200',
      compact ? 'p-4' : 'p-6'
    ]">
      <router-link
        to="/articles"
        class="text-sm font-medium text-primary-600 hover:text-primary-500"
      >
        View all articles →
      </router-link>
    </div>

    <!-- Delete Confirmation Modal -->
    <div
      v-if="showDeleteModal"
      class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50"
      @click="showDeleteModal = false"
    >
      <div
        class="relative top-20 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white"
        @click.stop
      >
        <div class="mt-3">
          <h3 class="text-lg font-medium text-gray-900 text-center mb-4">Delete Confirmation</h3>
          <p class="text-sm text-gray-500 text-center mb-6">
            Are you sure you want to delete this article?
          </p>
          <div class="flex justify-end space-x-3">
            <button
              type="button"
              @click="showDeleteModal = false"
              class="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50"
            >
              Cancel
            </button>
            <button
              @click="confirmDelete"
              :disabled="deletingArticle[articleToDelete?.id]"
              class="px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-red-600 hover:bg-red-700 disabled:opacity-50"
            >
              <span v-if="deletingArticle[articleToDelete?.id]" class="spinner-sm mr-2"></span>
              Delete
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- OpenAI Key Dialog -->
    <OpenAIKeyDialog
      :is-open="showOpenAIKeyDialog"
      :is-required="true"
      @close="showOpenAIKeyDialog = false"
      @saved="onOpenAIKeySaved"
    />
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { useAppStore } from '@/stores/app'
import { articleService } from '@/services/articles'
import OpenAIKeyDialog from '@/components/OpenAIKeyDialog.vue'
import {
  NewspaperIcon,
  PlusIcon,
  ArrowTopRightOnSquareIcon,
  TrashIcon
} from '@heroicons/vue/24/outline'

console.log('ArticlesList component loaded')

const appStore = useAppStore()

const props = defineProps({
  articles: {
    type: Array,
    default: () => []
  },
  loading: {
    type: Boolean,
    default: false
  },
  compact: {
    type: Boolean,
    default: false
  },
  limit: {
    type: Number,
    default: null
  },
  showActions: {
    type: Boolean,
    default: true
  },
  showDeleteButton: {
    type: Boolean,
    default: true
  },
  showViewMore: {
    type: Boolean,
    default: false
  },
  showBrowseButton: {
    type: Boolean,
    default: true
  },
  emptyStateTitle: {
    type: String,
    default: 'No articles yet'
  },
  emptyStateDescription: {
    type: String,
    default: 'Subscribe to some feeds to start seeing articles here.'
  }
})

const emit = defineEmits([
  'articleDeleted',
  'articleUpdated'
])

// Modal state
const showDeleteModal = ref(false)
const articleToDelete = ref(null)
const showOpenAIKeyDialog = ref(false)
const pendingSummaryArticleId = ref(null)

// Internal state for operations
const generatingSummary = ref({})
const deletingArticle = ref({})

// Generate summary for article
const generateSummary = async (articleId) => {
  console.log('ArticlesList: generateSummary called for article:', articleId)
  generatingSummary.value[articleId] = true
  
  try {
    const response = await articleService.generateSummary(articleId)
    console.log('Summary response:', response) // Debug log
    
    // Find the article in our reactive array
    const articleIndex = props.articles.findIndex(a => a.id === articleId)
    if (articleIndex === -1) {
      console.error('Article not found for ID:', articleId)
      appStore.showError('Article not found')
      return
    }
    
    // Parse the summary data from the response
    let summaryData = null
    if (response.data && response.data.summary) {
      summaryData = response.data.summary
    } else if (response.summary) {
      summaryData = response.summary
    } else {
      console.error('Invalid response structure:', response)
      appStore.showError('Invalid response from server')
      return
    }
    
    // Create the updated article with summary
    const updatedArticle = {
      ...props.articles[articleIndex],
      hasSummary: true,
      summary: {
        id: summaryData.id,
        text: summaryData.summaryText,
        aiModel: summaryData.aiModel,
        createdAt: summaryData.createdAt,
      }
    }
    
    console.log('Article updated with summary:', updatedArticle.summary) // Debug log
    appStore.showSuccess('Summary generated successfully!')
    
    // Emit the updated article to parent
    emit('articleUpdated', updatedArticle)
    
  } catch (error) {
    console.error('Error generating summary:', error)
    
    // Check if it's an OpenAI API key error
    if (error.code === 'OPENAI_API_KEY_REQUIRED') {
      pendingSummaryArticleId.value = articleId
      showOpenAIKeyDialog.value = true
      return
    }
    
    appStore.showError(error.response?.data?.message || error.message || 'Failed to generate summary')
  } finally {
    generatingSummary.value[articleId] = false
  }
}

// Handle OpenAI key saved event
const onOpenAIKeySaved = () => {
  appStore.showSuccess('OpenAI API key saved successfully!')
  showOpenAIKeyDialog.value = false
  
  // Retry the pending summary generation
  if (pendingSummaryArticleId.value) {
    const articleId = pendingSummaryArticleId.value
    pendingSummaryArticleId.value = null
    generateSummary(articleId)
  }
}

// Delete article
const deleteArticle = async (articleId) => {
  console.log('ArticlesList: deleteArticle called with ID:', articleId)
  deletingArticle.value[articleId] = true
  
  try {
    console.log('ArticlesList: Making API call to delete article:', articleId)
    await articleService.deleteArticle(articleId)
    console.log('ArticlesList: Article deleted successfully:', articleId)
    
    appStore.showSuccess('Article deleted successfully!')
    
    // Emit deletion to parent so it can update its local state
    emit('articleDeleted', articleId)
    
  } catch (error) {
    console.error('ArticlesList: Error deleting article:', error)
    console.error('ArticlesList: Error response:', error.response?.data)
    appStore.showError(error.response?.data?.message || 'Failed to delete article')
  } finally {
    deletingArticle.value[articleId] = false
  }
}

// Handle delete click - show confirmation modal
const handleDeleteClick = (articleId) => {
  console.log('ArticlesList: handleDeleteClick called with ID:', articleId)
  const article = props.articles.find(a => a.id === articleId)
  if (!article) {
    console.error('ArticlesList: Article not found for ID:', articleId)
    return
  }
  
  console.log('ArticlesList: Showing delete confirmation modal for:', article.title)
  articleToDelete.value = article
  showDeleteModal.value = true
}

// Confirm delete after modal confirmation
const confirmDelete = async () => {
  if (!articleToDelete.value) return
  
  console.log('ArticlesList: Confirming delete for article:', articleToDelete.value.id)
  
  // Call internal delete function
  await deleteArticle(articleToDelete.value.id)
  
  // Close modal and reset state
  showDeleteModal.value = false
  articleToDelete.value = null
}

const displayedArticles = computed(() => {
  console.log('Computing displayed articles:', props.articles.length, 'limit:', props.limit)
  if (props.limit && props.articles.length > props.limit) {
    return props.articles.slice(0, props.limit)
  }
  return props.articles
})

onMounted(() => {
  console.log('ArticlesList mounted with articles:', props.articles.length)
  
  // Clean up any unwanted elements that might be injected
  const cleanupUnwantedElements = () => {
    // Remove elements containing specific problematic text
    const textPatterns = ['[', ']', '"', '"', '+', 'more']
    textPatterns.forEach(pattern => {
      const elements = Array.from(document.querySelectorAll('*')).filter(el => 
        el.textContent && el.textContent.trim() === pattern
      )
      elements.forEach(el => {
        if (el && el.parentNode) {
          console.log('Removing unwanted element:', el.textContent, el)
          el.remove()
        }
      })
    })
    
    // Remove small positioned elements without classes
    const positionedElements = document.querySelectorAll('div:not([class]):not([id])[style*="position"]')
    positionedElements.forEach(el => {
      console.log('Removing positioned element:', el)
      el.remove()
    })
  }
  
  // Run cleanup immediately and then periodically
  cleanupUnwantedElements()
  
  // Set up a mutation observer to clean up dynamically added elements
  const observer = new MutationObserver((mutations) => {
    let shouldCleanup = false
    mutations.forEach((mutation) => {
      if (mutation.type === 'childList' && mutation.addedNodes.length > 0) {
        shouldCleanup = true
      }
    })
    if (shouldCleanup) {
      setTimeout(cleanupUnwantedElements, 100)
    }
  })
  
  observer.observe(document.body, {
    childList: true,
    subtree: true
  })
  
  // Cleanup observer on unmount
  const cleanup = () => observer.disconnect()
  return cleanup
})

// Format date helper
const formatDate = (dateString) => {
  return new Date(dateString).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: props.compact ? undefined : '2-digit',
    minute: props.compact ? undefined : '2-digit'
  })
}

// Clean article content helper
const cleanContent = (content) => {
  if (!content) return 'No description available.'
  
  console.log('Original content:', content) // Debug log
  
  // Remove HTML tags
  let cleaned = content.replace(/<[^>]*>/g, '')
  
  // Decode common HTML entities
  cleaned = cleaned
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#91;/g, '[')
    .replace(/&#93;/g, ']')
    .replace(/&hellip;/g, '...')
    .replace(/&nbsp;/g, ' ')
    .replace(/&ldquo;/g, '"')
    .replace(/&rdquo;/g, '"')
    .replace(/&lsquo;/g, "'")
    .replace(/&rsquo;/g, "'")
    .replace(/&mdash;/g, '—')
    .replace(/&ndash;/g, '–')
  
  // Remove any remaining HTML entities with numeric codes
  cleaned = cleaned.replace(/&#\d+;/g, '')
  
  // Remove extra whitespace and trim
  cleaned = cleaned.replace(/\s+/g, ' ').trim()
  
  console.log('Cleaned content:', cleaned) // Debug log
  
  return cleaned || 'No description available.'
}
</script>

<style scoped>
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.line-clamp-3 {
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

/* Enhanced readability font stack */
.font-reading {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Inter', 'Helvetica Neue', sans-serif;
  font-feature-settings: 'kern' 1, 'liga' 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizeLegibility;
}

.spinner {
  border: 2px solid #f3f3f3;
  border-top: 2px solid #3498db;
  border-radius: 50%;
  width: 20px;
  height: 20px;
  animation: spin 1s linear infinite;
}

.spinner-sm {
  border: 1px solid #f3f3f3;
  border-top: 1px solid #3498db;
  border-radius: 50%;
  width: 12px;
  height: 12px;
  animation: spin 1s linear infinite;
  display: inline-block;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

/* Hide potential browser extension injected elements */
.article-content *[class*="extension"],
.article-content *[class*="share"],
.article-content *[class*="social"],
.article-content *[id*="extension"],
.article-content script,
.article-content iframe {
  display: none !important;
}

/* Hide elements that might be injected with inline styles */
.article-content > div[style*="position: absolute"],
.article-content > div[style*="position: fixed"],
.article-content > div[style*="z-index"] {
  display: none !important;
}

/* Hide specific problematic elements that show brackets and quotes */
*[data-*="share"],
*[class*="share-button"],
*[class*="social-button"],
*[class*="extension"],
*[id*="extension"],
button[style*="position: absolute"],
div[style*="border-radius"][style*="background"],
div[style*="position: absolute"][style*="top"][style*="left"],
div[style*="position: fixed"][style*="top"][style*="left"] {
  display: none !important;
  visibility: hidden !important;
}

/* Target elements that might be floating or positioned over content */
body > div[style*="position: fixed"]:not([class]),
body > div[style*="position: absolute"][style*="z-index"]:not([class]),
div[style*="transform"][style*="position: fixed"]:not([class]) {
  display: none !important;
  visibility: hidden !important;
}

/* Hide any small positioned elements that might be injected */
div:not([class]):not([id])[style*="position"],
span:not([class]):not([id])[style*="position"] {
  display: none !important;
  visibility: hidden !important;
}

/* Hide elements with very specific styling patterns common to extensions */
div[style*="border-radius: 50%"],
div[style*="width: 24px"],
div[style*="height: 24px"] {
  display: none !important;
  visibility: hidden !important;
}
</style>